---
# Se crea un directorio para montar la unidad NFS
- name: Create a volume group 
  lvg:
    vg: data_vg
    pvs: /dev/sdb

# Se crea un volumen logico
- name: Create a logical volume 
  lvol:
    vg: data_vg
    lv: nfs_lv
    size: '2559'
    force: yes

# Crea el filesystem de tipo xfs
- name: create filesystem xfs type
  filesystem: 
    fstype: xfs  
    dev: /dev/data_vg/nfs_lv
    force: yes

# Crea el punto de montaje 
- name: Create mountable dir
  file: 
    path: /srv/nfs 
    state: directory 
    mode: 777 
    owner: ansible 
    group: ansible

# Monta el volumen
- name: Mount a volume
  mount:
    path: /srv/nfs
    src: /dev/data_vg/nfs_lv
    opts: defaults
    state: mounted
    fstype: xfs