---
- name: identifica el primer disco libre
  set_fact:
    disks: "/dev/{{ item.key }}"
  when:
    # si el disco no está particionado tendrá libre 
    # estas variables de los facts
    - not item.value.partitions
    - not item.value.holders
    - not item.value.links.uuids
    - not item.value.links.labels
    # los discos serán /dev/vd? o /dev/sd? filtramos el
    # resto de resultados
    - item.key | regex_search ("vd|sd")
  with_dict: "{{ ansible_devices }}"

# Se crea un directorio para montar la unidad NFS
- name: Create a volume group 
  lvg:
    vg: data_vg
    pvs: "{{ disks }}"

# Se crea un volumen logico
- name: Create a logical volume 
  lvol:
    vg: data_vg
    lv: nfs_lv
    size: '2559'
    force: yes

# Crea el filesystem de tipo xfs
- name: create filesystem xfs type
  filesystem: 
    fstype: xfs  
    dev: /dev/data_vg/nfs_lv
    force: yes

# Crea el punto de montaje 
- name: Create mountable dir
  file: 
    path: /srv/nfs 
    state: directory 
    mode: 777 
    owner: root 
    group: root

# Monta el volumen
- name: Mount a volume
  mount:
    path: /srv/nfs
    src: /dev/data_vg/nfs_lv
    opts: defaults
    state: mounted
    fstype: xfs