--- 
# Copia el template de export exports.j2
- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

# Recarga el fichero /etc/exports para aplicar la nueva configuración
- name: Reload /etc/exports
  command: exportfs -r