---
######################################################################
# Preparación e instalacion de la imagen docker de rabbitmq

# Creamos un namespace para la instalación
- name: Create namespace for rabbit
  shell: kubectl create namespace rabbit

# Crea un persistent volume mediante el fichero nfs-pv.yaml
- name: Create persistent volume
  shell: kubectl apply -f /home/nfs-pv.yaml

# Crea un persistent volume claim mediante el fichero nfs-pvc.yaml
- name: Create persistent volume claim
  shell: kubectl apply -f /home/nfs-pvc.yaml

# Instala rabbitmq mediante el fichero de despliegue rabbit.yaml
- name: Install rabbit image
  shell: kubectl apply -f /home/rabbit.yaml

