######################################################################
# Realiza la conifguración e instalación de Kubernetes y Docker en 
# los nodos master y workers
---
- name: config environments
  hosts: master,worker
  vars_files:
    - "group_vars/config.yaml"
  gather_facts: false
  become: yes
  roles:
    - dns
    - newtwork-kubernetes
    - swap
    - docker-install
    - kubernetes-install

######################################################################
# Configura Kubernetes en el nodo master e instala un CDN
- name: config master
  hosts: master
  vars_files:
    - "group_vars/config.yaml"
  gather_facts: true
  become: true
  roles:
    - kbt-master-config
    - cdn-install

######################################################################
# Une los nodos worker al master de Kubernetes y 
# realiza la configuración
- name: config workers
  hosts: worker
  vars_files:
    - "group_vars/config.yaml"
  gather_facts: true
  become: true
  roles:
    - kbt-worker-config


