######################################################################
# Instala una imagen de RabbitMQ sobre la instalación de kubernetes
--- 
- name: Install rabbit
  hosts: master
  vars_files:
    - "group_vars/config.yaml"
  become: true
  roles:
    - rabbit-install

